version: "3.3"

services:
  dbot-web:
    image: dbot-web:latest
    command: daphne -u /tmp/daphne.sock dbot.asgi:application
    restart: unless-stopped
    env_file:
      - dbot/.env
    ports:
    - "127.0.0.1:4322:4322"
    depends_on:
      - db
      - redis
    volumes:
      - ~/dbot_data/uploads:/app/uploads
      - /tmp:/tmp

  jsdbot:
    image: jsdbot:latest
    command: node dist/index.js
    restart: unless-stopped
    env_file:
      - dbot/jsdbot.env
    depends_on:
      - redis

  redis:
    image: redis

  db:
    image: postgres:12
    restart: unless-stopped
    env_file:
      - dbot/.env
    volumes:
      - ~/dbot_data/db:/var/lib/postgresql/data
