# Generated by Django 3.1.2 on 2020-10-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_id', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('file', models.FileField(upload_to='uploads/cache/')),
                ('size', models.IntegerField()),
            ],
        ),
    ]
