# Generated by Django 3.1.2 on 2020-10-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0002_CachedStream'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('color', models.CharField(choices=[
                    ('lightSalmon', 'Red'), ('steelBlue', 'SteelBlue'), ('paleGreen', 'Green'),
                    ('lemonChiffon', 'Yellow'), ('gainsBoro', 'Gray'), ('plum', 'Violet'), ('orchid', 'Orchid'),
                    ('coral', 'Orange'), ('mediumSlateBlue', 'Purple')],
                    max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='soundeffect',
            name='sound_effect',
            field=models.FileField(upload_to='uploads/soundeffects/'),
        ),
        migrations.AddField(
            model_name='soundeffect',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='sound_effects', to='sounds.Category'),
        ),
    ]
