# Generated by Django 3.1.2 on 2020-11-08 08:03

import colorfield.fields
from django.db import migrations


def do_nothing(apps, schema_editor):
    pass


def move_colors(apps, schema_editor):
    color_map = {
        "lightSalmon": "#FFA07A",
        "steelBlue": "#4682B4",
        "paleGreen": "#98FB98",
        "lemonChiffon": "#FFFACD",
        "gainsBoro": "#DCDCDC",
        "plum": "#DDA0DD",
        "orchid": "#DA70D6",
        "coral": "#FF7F50",
        "mediumSlateBlue": "#7B68EE",
    }

    Category = apps.get_model("sounds", "Category")
    for category in Category.objects.all():
        category.color_code = color_map[category.color]
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0003_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color_code',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.RunPython(move_colors, do_nothing),
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
    ]
