# Generated by Django 3.1.2 on 2020-11-08 09:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0004_colorfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='text_color_code',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
