# Generated by Django 3.1.2 on 2020-11-15 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sounds', '0005_category_text_color_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_lists', to=settings.AUTH_USER_MODEL)),
                ('sound_effects', models.ManyToManyField(related_name='favourite_lists', to='sounds.SoundEffect')),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
