# Generated by Django 3.1.4 on 2021-01-03 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sounds', '0008_discorduser_and_event_sounds'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwEventSoundEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('double_kill', 'Double Kill'), ('triple_kill', 'Triple Kill'), ('quadruple_kill', 'Quadruple Kill'), ('quintuple_kill', 'Quintuple Kill'), ('sextuple_kill', 'Sextuple Kill'), ('team_kill', 'Team Kill')], max_length=64)),
                ('hero', models.CharField(blank=True, choices=[('Ana', 'Ana'), ('Ashe', 'Ashe'), ('Baptiste', 'Baptiste'), ('Bastion', 'Bastion'), ('Brigitte', 'Brigitte'), ('Doomfist', 'Doomfist'), ('Dva', 'Dva'), ('Echo', 'Echo'), ('Genji', 'Genji'), ('Hanzo', 'Hanzo'), ('Junkrat', 'Junkrat'), ('Lucio', 'Lucio'), ('Mcree', 'Mcree'), ('Mei', 'Mei'), ('Mercy', 'Mercy'), ('Moira', 'Moira'), ('Orisa', 'Orisa'), ('Pharah', 'Pharah'), ('Reaper', 'Reaper'), ('Reinhardt', 'Reinhardt'), ('Roadhog', 'Roadhog'), ('Sigma', 'Sigma'), ('Soldier', 'Soldier'), ('Sombra', 'Sombra'), ('Symmetra', 'Symmetra'), ('Torbjorn', 'Torbjorn'), ('Tracer', 'Tracer'), ('Widowmaker', 'Widowmaker'), ('Winston', 'Winston'), ('Wreckingball', 'Wreckingball'), ('Zarya', 'Zarya'), ('Zenyatta', 'Zenyatta')], max_length=64, null=True)),
                ('team', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue')], max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sound_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.soundeffect')),
            ],
        ),
    ]
