# Generated by Django 3.1.6 on 2021-02-06 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sounds', '0009_owevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundEffectPlayHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('played_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sound_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to='sounds.soundeffect')),
            ],
            options={
                'index_together': {('sound_effect', 'played_by', 'played_at')},
            },
        ),
    ]
