# Generated by Django 3.1.6 on 2021-02-14 08:23
from django.db import migrations
from django.contrib.auth.management import create_permissions


def add_groups_and_permissions(apps, _):
    # Make sure permissions are added
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    groups = [
        {
            "name": "Bot user",
            "permissions": ["can_play_sound_with_bot",
                            "can_download_sound",
                            "can_manage_own_favourites"]
        },
        {
            "name": "Sound manager",
            "permissions": ["add_alternativename",
                            "change_alternativename",
                            "delete_alternativename",
                            "view_alternativename",
                            "add_category",
                            "change_category",
                            "delete_category",
                            "view_category",
                            "add_eventtriggeredsoundeffect",
                            "change_eventtriggeredsoundeffect",
                            "delete_eventtriggeredsoundeffect",
                            "view_eventtriggeredsoundeffect",
                            "add_oweventsoundeffect",
                            "change_oweventsoundeffect",
                            "delete_oweventsoundeffect",
                            "view_oweventsoundeffect",
                            "add_soundeffect",
                            "change_soundeffect",
                            "delete_soundeffect",
                            "view_soundeffect",
                            "add_soundeffectgif",
                            "change_soundeffectgif",
                            "delete_soundeffectgif",
                            "view_soundeffectgif",
                            "view_soundeffectplayhistory",
                            "can_play_sound_with_bot",
                            "can_download_sound",
                            "can_manage_own_favourites",
                            "can_upload_clip_from_yt",
                            ]
        }
    ]
    for g in groups:
        group = Group.objects.get_or_create(name=g["name"])[0]
        for codename in g["permissions"]:
            group.permissions.add(Permission.objects.get(codename=codename))


def do_nothing(*_):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('sounds', '0011_permissions'),
    ]

    operations = [
        migrations.RunPython(add_groups_and_permissions, do_nothing)
    ]
