# Generated by Django 3.1.7 on 2021-03-24 21:22

from django.db import migrations


def create_default_category(apps, _):
    default_category_name = "No category"
    Category = apps.get_model("sounds", "Category")
    if not Category.objects.filter(name=default_category_name).exists():
        Category.objects.create(name=default_category_name, color_code="#F8F8F8")


def do_nothing(*_):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0012_permissions_to_groups'),
    ]

    operations = [
        migrations.RunPython(create_default_category, do_nothing)
    ]
