# Generated by Django 3.2.14 on 2022-07-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0013_default_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cachedstream',
            old_name='title',
            new_name='name',
        ),
    ]
