# Generated by Django 3.2.14 on 2022-07-29 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0014_CachedStream_rename_title_to_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soundeffect',
            old_name='sound_effect',
            new_name='file',
        ),
    ]
