# Generated by Django 4.1 on 2022-10-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0018_alter_oweventsoundeffect_event_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwEventSoundEffect',
        ),
    ]
