# Generated by Django 3.2.15 on 2022-08-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SttReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='This reaction is not used if not active')),
                ('cooldown', models.FloatField(default=5.0, help_text='How many seconds until this can be triggered again')),
                ('data', models.JSONField(help_text='Format of this depends on the ReactionType')),
            ],
        ),
    ]
