# Generated by Django 4.1 on 2022-10-23 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sounds', '0019_OW_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue')], max_length=64, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ow.gameevent')),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ow.hero')),
                ('sound_effects', models.ManyToManyField(blank=True, null=True, to='sounds.soundeffect')),
            ],
        ),
        migrations.AddConstraint(
            model_name='eventreaction',
            constraint=models.UniqueConstraint(fields=('event', 'hero', 'team'), name='unique_with_optional'),
        ),
        migrations.AddConstraint(
            model_name='eventreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('hero', None)), fields=('event', 'team'), name='unique_without_hero', violation_error_message='Event reaction with this Event, Hero and Team already exists.'),
        ),
        migrations.AddConstraint(
            model_name='eventreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('team', None)), fields=('event', 'hero'), name='unique_without_team', violation_error_message='Event reaction with this Event, Hero and Team already exists.'),
        ),
        migrations.AddConstraint(
            model_name='eventreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('hero', None), ('team', None)), fields=('event',), name='unique_without_hero_and_team', violation_error_message='Event reaction with this Event, Hero and Team already exists.'),
        ),
    ]
