# Generated by Django 4.1 on 2022-10-23 17:05
from enum import Enum

from django.db import migrations

from ow import models


class Event(Enum):
    DOUBLE_KILL = "double_kill"
    TRIPLE_KILL = "triple_kill"
    QUADRUPLE_KILL = "quadruple_kill"
    QUINTUPLE_KILL = "quintuple_kill"
    SEXTUPLE_KILL = "sextuple_kill"
    TEAM_KILL = "team_kill"
    HOOK_KILL = "hook_kill"
    CRITICAL_HIT = "critical_hit"


class HeroEnum(Enum):
    ANA = "Ana"
    ASHE = "Ashe"
    BAPTISTE = "Baptiste"
    BASTION = "Bastion"
    BRIGITTE = "Brigitte"
    DOOMFIST = "Doomfist"
    DVA = "Dva"
    ECHO = "Echo"
    GENJI = "Genji"
    HANZO = "Hanzo"
    JUNKERQUEEN = "Junkerqueen"
    JUNKRAT = "Junkrat"
    LUCIO = "Lucio"
    KIRIKO = "Kiriko"
    MCREE = "Mcree"
    MEI = "Mei"
    MERCY = "Mercy"
    MOIRA = "Moira"
    ORISA = "Orisa"
    PHARAH = "Pharah"
    REAPER = "Reaper"
    REINHARDT = "Reinhardt"
    ROADHOG = "Roadhog"
    SIGMA = "Sigma"
    SOLDIER = "Soldier"
    SOJOURN = "Sojourn"
    SOMBRA = "Sombra"
    SYMMETRA = "Symmetra"
    TORBJORN = "Torbjorn"
    TRACER = "Tracer"
    WIDOWMAKER = "Widowmaker"
    WINSTON = "Winston"
    WRECKINGBALL = "Wreckingball"
    ZARYA = "Zarya"
    ZENYATTA = "Zenyatta"


def do_nothing(apps, schema_editor):
    pass

def create_initial_heroes(apps, schema_editor):
    Hero = apps.get_model("ow", "Hero")

    for h in HeroEnum:
        Hero.objects.create(name=h.value)

def create_initial_game_events(apps, schema_editor):
    GameEvent = apps.get_model("ow", "GameEvent")

    for e in Event:
        GameEvent.objects.create(name=e.value)


def create_initial_reactions(apps, schema_editor):
    EventReaction = apps.get_model("ow", "EventReaction")
    GameEvent = apps.get_model("ow", "GameEvent")
    for e in GameEvent.objects.all():
        for team in models.Team:
            EventReaction.objects.create(event=e, team=team, created_by=None)


class Migration(migrations.Migration):

    dependencies = [
        ('ow', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_heroes, do_nothing),
        migrations.RunPython(create_initial_game_events, do_nothing),
        migrations.RunPython(create_initial_reactions, do_nothing),
    ]
